assTemplate='''
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Last Style Storage: Default
Audio File: Gorilla60fps.mpeg
Video File: Gorilla60fps.mpeg
Video AR Mode: 4
Video AR Value: 1.777778
Video Zoom Percent: 0.375000
Scroll Position: 84
Active Line: 109
Video Position: 12317

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: holy夏哥,.黑体-日本语,80,&H00FFFFFF,&H000000FF,&H153397FF,&HFFFFFFFF,0,0,0,0,100,100,0,0,1,4,0,2,10,10,10,1
Style: fbk,.黑体-日本语,60,&H00FFFFFF,&H000000FF,&H15FFAA40,&HFFFFFFFF,-1,0,0,0,100,100,0,0,1,2,2,7,10,10,10,128
Style: 心心,.黑体-日本语,80,&H00FFFFFF,&H000000FF,&H004551FF,&H00000000,0,0,0,0,100,100,0,0,1,6,0,2,10,10,10,1
Style: 混合旁白,.黑体-日本语,80,&H00FFFFFF,&H001415DB,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,5,0,2,10,10,10,1
Style: 心心封面,.黑体-日本语,160,&H00FFFFFF,&H000000FF,&H004551FF,&H00000000,-1,0,0,0,100,100,0,0,1,18,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''

assDialogue="Dialogue: 0,0:00:00.24,0:00:02.97,holy夏哥,,0,0,0,,干点什么 玩点能减肥的吧"